apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "test-lab"
spec:
  title: "Workshop"
  description: "Workshop description."
  # publish:
  #   image: "ghcr.io/DEPI-DevOps/test-lab-files:latest"
  workshop:
    files:
    - git:
        url: https://github.com/DEPI-DevOps/educates-workshop
        ref: origin/main
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
      editor:
        enabled: true
      docker:
        enabled: false
      examiner:
        enabled: true
      registry:
        enabled: false
