apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "test-lab"
spec:
  title: "Workshop"
  description: "Workshop description."
  publish:
    image: "docker.io/sh3b0/test-lab-files:latest"
  workshop:
    files:
    - image:
        url: "docker.io/sh3b0/test-lab-files:latest"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
      editor:
        enabled: true
      docker:
        enabled: false
      examiner:
        enabled: true
      registry:
        enabled: false
