name: Publish Workshop

on:
  push:
    tags:
      - "v[0-9]+"

jobs:
  publish-workshop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Publish Workshop
        uses: educates/educates-github-actions/publish-workshop@v7
        with:
          token: ${{ secrets.CR_PAT }}
